# Generated by Django 2.2.1 on 2019-08-02 17:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='', max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RentingUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_rooms', models.IntegerField()),
                ('price', models.CharField(default='', max_length=50)),
                ('maximum_no_of_occupants', models.IntegerField()),
                ('attached_bathroom', models.CharField(choices=[('sh', 'Shared'), ('in', 'Individual')], default='no', max_length=3)),
                ('attached_kitchen', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=15)),
                ('drive_in', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('parking', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('water_bill_included', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('electricity_bill_included', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('preferred_customer', models.CharField(choices=[('Family Preferred', 'Family Preferred'), ('Working Preferred', 'Working Preferred'), ('Student Preferred', 'Student Preferred'), ('no', 'No Such Preference')], default='no', max_length=50)),
                ('gender_preference', models.CharField(choices=[('Only Girls', 'Only Girls'), ('Only Boys', 'Only Boys'), ('no', 'No Gender Preference')], default='no', max_length=50)),
                ('alternate_contact_number', models.CharField(blank=True, default='', max_length=10)),
                ('preferred_contact_time', models.CharField(default='', max_length=50)),
                ('any_other', models.TextField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('approved', models.BooleanField(default=False)),
                ('locality', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Location')),
                ('user_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='RentingPGUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupants_per_room', models.IntegerField()),
                ('price', models.CharField(default='', max_length=50)),
                ('attached_bathroom', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('food_included', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=15)),
                ('drive_in', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('parking', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('water_bill_included', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('electricity_bill_included', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('preferred_customer', models.CharField(choices=[('Working Preferred', 'Working Preferred'), ('Student Preferred', 'Student Preferred'), ('no ', 'No Preference ')], default='no', max_length=50)),
                ('gender_preference', models.CharField(choices=[('Only Girls', 'Only Girls'), ('Only Boys', 'Only Boys')], default='', max_length=50)),
                ('preferred_contact_time', models.CharField(default='', max_length=50)),
                ('alternate_contact_number', models.CharField(blank=True, default='', max_length=10)),
                ('any_other', models.TextField(blank=True, default='', max_length=100)),
                ('timings', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('approved', models.BooleanField(default=False)),
                ('locality', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Location')),
                ('user_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='ImagesPG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=main.models.user_directory_path_pg, verbose_name='ImagePG')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.RentingPGUser')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=main.models.user_directory_path, verbose_name='Image')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.RentingUser')),
            ],
        ),
    ]
