# Generated by Django 2.0.13 on 2019-06-14 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/', verbose_name='Image')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.RentingUser')),
            ],
        ),
    ]
