# Generated by Django 2.0.13 on 2019-06-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentingPGUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupants_per_room', models.IntegerField()),
                ('price', models.CharField(default='', max_length=50)),
                ('locality', models.CharField(default='', max_length=100)),
                ('attached_bathroom', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='', max_length=3)),
                ('attached_kitchen', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='', max_length=15)),
                ('drive_in', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='', max_length=3)),
                ('parking', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='', max_length=3)),
                ('water_bill_included', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='', max_length=3)),
                ('electricity_bill_included', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='', max_length=3)),
                ('preferred_customer', models.CharField(choices=[('family', 'Family'), ('student', 'Student'), ('others (Specify)', 'Others (Specify)'), ('no such preference', 'No Such Preference')], default='', max_length=50)),
                ('gender_preference', models.CharField(choices=[('only female', 'Only Female'), ('only male', 'Only Male'), ('none', 'None')], default='', max_length=10)),
                ('preferred_contact_time', models.CharField(default='', max_length=50)),
                ('contact_number', models.CharField(default='', max_length=10)),
                ('alternate_contact_number', models.CharField(default='', max_length=10)),
                ('any_other', models.TextField(blank=True, default='', max_length=100)),
                ('timings', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='rentinguser',
            old_name='people_per_room',
            new_name='maximum_no_of_occupants',
        ),
        migrations.RemoveField(
            model_name='rentinguser',
            name='Paying_guest',
        ),
        migrations.RemoveField(
            model_name='rentinguser',
            name='balcony',
        ),
        migrations.RemoveField(
            model_name='rentinguser',
            name='contact_time',
        ),
        migrations.RemoveField(
            model_name='rentinguser',
            name='food',
        ),
        migrations.RemoveField(
            model_name='rentinguser',
            name='gender_pref',
        ),
        migrations.RemoveField(
            model_name='rentinguser',
            name='individual',
        ),
        migrations.RemoveField(
            model_name='rentinguser',
            name='kitchen',
        ),
        migrations.RemoveField(
            model_name='rentinguser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='rentinguser',
            name='prefered_customer',
        ),
        migrations.AddField(
            model_name='rentinguser',
            name='alternate_contact_number',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='rentinguser',
            name='any_other',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='rentinguser',
            name='attached_kitchen',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='rentinguser',
            name='drive_in',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='', max_length=3),
        ),
        migrations.AddField(
            model_name='rentinguser',
            name='electricity_bill_included',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='', max_length=3),
        ),
        migrations.AddField(
            model_name='rentinguser',
            name='gender_preference',
            field=models.CharField(choices=[('only female', 'Only Female'), ('only male', 'Only Male'), ('none', 'None')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='rentinguser',
            name='preferred_contact_time',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='rentinguser',
            name='preferred_customer',
            field=models.CharField(choices=[('family', 'Family'), ('student', 'Student'), ('others (Specify)', 'Others (Specify)'), ('no such preference', 'No Such Preference')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='rentinguser',
            name='price',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='rentinguser',
            name='water_bill_included',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='rentinguser',
            name='attached_bathroom',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='rentinguser',
            name='contact_number',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='rentinguser',
            name='locality',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='rentinguser',
            name='parking',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='', max_length=3),
        ),
    ]
