# Generated by Django 2.2.2 on 2019-10-20 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191020_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagespg',
            name='room_pg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.RentingPGUser'),
        ),
        migrations.AlterField(
            model_name='imagespg',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
    ]
