# Generated by Django 2.0.13 on 2019-06-15 17:13

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190615_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to=main.models.user_directory_path, verbose_name='Image'),
        ),
    ]
