# Generated by Django 2.0.13 on 2019-06-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_imagespg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentinguser',
            name='alternate_contact_number',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='rentinguser',
            name='any_other',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
    ]
