# Generated by Django 2.2.2 on 2019-07-01 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190622_1737'),
        ('main', '0007_auto_20190617_1002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentingpguser',
            old_name='attached_kitchen',
            new_name='food_included',
        ),
        migrations.AddField(
            model_name='rentingpguser',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
        migrations.AddField(
            model_name='rentinguser',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='rentingpguser',
            name='alternate_contact_number',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='rentingpguser',
            name='gender_preference',
            field=models.CharField(choices=[('Female Preferred', 'Females Preferred'), ('Males Preferred', 'Males Preferred'), ('No Gender Preference', 'No Gender Preference')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rentingpguser',
            name='preferred_customer',
            field=models.CharField(choices=[('Family Preferred', 'Family Preferred'), ('Student Preferred', 'Student Preferred'), ('No Preference For Customer', 'No Preference for Customer')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rentinguser',
            name='gender_preference',
            field=models.CharField(choices=[('Female Preferred', 'Females Preferred'), ('Males Preferred', 'Males Preferred'), ('No Gender Preference', 'No Gender Preference')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rentinguser',
            name='preferred_customer',
            field=models.CharField(choices=[('Family Preferred', 'Family Preferred'), ('Student Preferred', 'Student Preferred'), ('No Such Preference for Customer', 'No Such Preference for Customer')], default='', max_length=50),
        ),
    ]
