# Generated by Django 2.2.2 on 2019-07-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190702_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentingpguser',
            name='gender_preference',
            field=models.CharField(choices=[('Only Girls', 'Only Girls'), ('Only Boys', 'Only Boys')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rentingpguser',
            name='preferred_customer',
            field=models.CharField(choices=[('Working Preferred', 'Working Preferred'), ('Student Preferred', 'Student Preferred'), ('No Preference ', 'No Preference ')], default='', max_length=50),
        ),
    ]
