# Generated by Django 2.2.2 on 2019-07-04 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190704_0810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentingpguser',
            name='contact_number',
        ),
    ]
