# Generated by Django 2.2.2 on 2019-07-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_rentingpguser_contact_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentinguser',
            name='contact_number',
        ),
        migrations.AlterField(
            model_name='rentinguser',
            name='attached_bathroom',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='rentinguser',
            name='attached_kitchen',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=15),
        ),
        migrations.AlterField(
            model_name='rentinguser',
            name='drive_in',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='rentinguser',
            name='electricity_bill_included',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='rentinguser',
            name='gender_preference',
            field=models.CharField(choices=[('Only Girls', 'Only Girls'), ('Only Boys', 'Only Boys'), ('no', 'No Gender Preference')], default='no', max_length=50),
        ),
        migrations.AlterField(
            model_name='rentinguser',
            name='parking',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='rentinguser',
            name='preferred_customer',
            field=models.CharField(choices=[('Family Preferred', 'Family Preferred'), ('Working Preferred', 'Working Preferred'), ('Student Preferred', 'Student Preferred'), ('no', 'No Such Preference for Customer')], default='no', max_length=50),
        ),
        migrations.AlterField(
            model_name='rentinguser',
            name='water_bill_included',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
    ]
