# Generated by Django 2.2.2 on 2019-07-04 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20190704_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.RemoveField(
            model_name='rentinguser',
            name='locality',
        ),
        migrations.AddField(
            model_name='rentinguser',
            name='locality',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Location'),
        ),
    ]
