# Generated by Django 2.0.13 on 2019-07-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20190704_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentingpguser',
            name='gender_preference',
            field=models.CharField(choices=[('Only Girls', 'Only Girls'), ('Only Boys', 'Only Boys'), ('No Preference', 'No Preference')], default='No Preference', max_length=50),
        ),
        migrations.AlterField(
            model_name='rentinguser',
            name='attached_bathroom',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Shared', 'Shared')], default='Shared', max_length=3),
        ),
    ]
