# Generated by Django 2.2.1 on 2019-07-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20190704_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentinguser',
            name='attached_bathroom',
            field=models.CharField(choices=[('sh', 'Shared'), ('in', 'Individual')], default='no', max_length=3),
        ),
    ]
