# Generated by Django 2.0.13 on 2019-07-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20190710_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentinguser',
            name='attached_bathroom',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Shared', 'Shared')], default='Shared', max_length=3, verbose_name='Bathroom Type'),
        ),
        migrations.AlterField(
            model_name='rentinguser',
            name='gender_preference',
            field=models.CharField(choices=[('Only Girls', 'Only Girls'), ('Only Boys', 'Only Boys'), ('no', 'No Gender Preference')], default='no', max_length=50, verbose_name='Only Boys/Girls'),
        ),
    ]
