# Generated by Django 2.0.13 on 2019-06-15 17:24

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190615_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesPG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=main.models.user_directory_path_pg, verbose_name='ImagePG')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.RentingPGUser')),
            ],
        ),
    ]
