# Generated by Django 2.0.13 on 2019-06-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190617_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentingpguser',
            name='gender_preference',
            field=models.CharField(choices=[('only female', 'Only Female'), ('only male', 'Only Male'), ('none', 'None')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rentinguser',
            name='gender_preference',
            field=models.CharField(choices=[('only female', 'Only Female'), ('only male', 'Only Male'), ('none', 'None')], default='', max_length=50),
        ),
    ]
