# Generated by Django 2.2.2 on 2019-07-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190704_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentingpguser',
            name='attached_bathroom',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='rentingpguser',
            name='drive_in',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='rentingpguser',
            name='electricity_bill_included',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='rentingpguser',
            name='food_included',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=15),
        ),
        migrations.AlterField(
            model_name='rentingpguser',
            name='parking',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='rentingpguser',
            name='preferred_customer',
            field=models.CharField(choices=[('Working Preferred', 'Working Preferred'), ('Student Preferred', 'Student Preferred'), ('no ', 'No Preference ')], default='no', max_length=50),
        ),
        migrations.AlterField(
            model_name='rentingpguser',
            name='water_bill_included',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='rentinguser',
            name='preferred_customer',
            field=models.CharField(choices=[('Family Preferred', 'Family Preferred'), ('Working Preferred', 'Working Preferred'), ('Student Preferred', 'Student Preferred'), ('no', 'No Such Preference')], default='no', max_length=50),
        ),
    ]
