# Generated by Django 2.2.2 on 2019-07-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20190704_0839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='rentinguser',
            name='locality',
        ),
        migrations.AddField(
            model_name='rentinguser',
            name='locality',
            field=models.ManyToManyField(to='main.Location'),
        ),
    ]
