# Generated by Django 2.2.2 on 2019-07-04 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20190704_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentingpguser',
            name='locality',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Location'),
        ),
    ]
