# Generated by Django 2.2.2 on 2019-07-04 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20190704_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentinguser',
            name='locality',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Location'),
        ),
    ]
