# Generated by Django 2.2.1 on 2019-12-27 08:24

from django.db import migrations, models
import django.db.models.deletion
import grocery.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_shop_owner'),
        ('grocery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='code',
            new_name='barcode',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product',
            new_name='name',
        ),
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(null=True, upload_to=grocery.models.brand_directory_path, validators=[grocery.models.validate_image], verbose_name='Brand Image'),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to=grocery.models.category_directory_path, validators=[grocery.models.validate_image], verbose_name='Category Image'),
        ),
        migrations.AddField(
            model_name='product',
            name='free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='free_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grocery.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='selling_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='alternate_no',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='email',
            field=models.EmailField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='image',
            field=models.ImageField(null=True, upload_to=grocery.models.shop_directory_path, validators=[grocery.models.validate_image], verbose_name='Shop Image'),
        ),
        migrations.AddField(
            model_name='shop',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_user',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='grocery.Brand'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, to='grocery.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='off',
            field=models.BooleanField(),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=grocery.models.product_directory_path, validators=[grocery.models.validate_image], verbose_name='Product Image')),
                ('product_image', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='grocery.Product')),
            ],
        ),
    ]
