# Generated by Django 2.2.1 on 2019-12-31 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0002_auto_20191227_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='free',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='off',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
