# Generated by Django 2.2.1 on 2019-12-31 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0003_auto_20191231_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='free',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='off',
            field=models.BooleanField(default=False),
        ),
    ]
