# Generated by Django 2.2.2 on 2019-12-25 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0004_brand_category_product_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='', max_length=40)),
            ],
        ),
        
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop', models.CharField(default='', max_length=40)),
                ('mobile_no', models.CharField(blank=True, max_length=12, null=True)),
                ('email', models.EmailField(blank=True, max_length=70, null=True)),
                ('shop_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40)),
                ('quantity', models.CharField(default='', max_length=10)),
                ('price', models.IntegerField(default='')),
                ('selling_price', models.IntegerField(default='')),
                ('off', models.BooleanField()),
                ('free', models.BooleanField()),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
                ('savings', models.IntegerField(blank=True, null=True)),
                ('barcode', models.IntegerField(blank=True, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='grocery.Brand')),
                ('category', models.ManyToManyField(blank=True, to='grocery.Category')),
                ('free_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grocery.Product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocery.Shop')),
            ],
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand',
            field=models.CharField(default='1', max_length=40),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='grocery.Brand'),
        ),
    ]
