# Generated by Django 2.2.1 on 2020-01-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0004_auto_20191231_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
