# Generated by Django 2.2.2 on 2019-12-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0006_auto_20191225_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='free',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='off',
            field=models.BooleanField(default=None),
        ),
    ]
