# Generated by Django 2.2.2 on 2019-12-26 08:58

from django.db import migrations, models
import grocery.models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0008_auto_20191226_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to=grocery.models.product_directory_path, validators=[grocery.models.validate_image], verbose_name='Product Image'),
        ),
    ]
