# Generated by Django 2.2.2 on 2019-12-26 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0009_auto_20191226_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
    ]
