# Generated by Django 2.2.2 on 2019-12-29 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0010_auto_20191226_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='free',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='off',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_user',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
    ]
