# Generated by Django 2.2.2 on 2019-12-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0011_auto_20191229_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='off',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
