# Generated by Django 2.2.2 on 2019-12-31 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0012_auto_20191229_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='grocery.Category'),
        ),
    ]
