# Generated by Django 2.2.2 on 2019-12-31 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0013_auto_20191231_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='free',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='off',
            field=models.BooleanField(default=False),
        ),
    ]
