# Generated by Django 2.2.2 on 2020-01-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0014_auto_20191231_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, to='grocery.Category'),
        ),
    ]
