# Generated by Django 2.2.2 on 2020-01-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0015_auto_20200106_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop',
            field=models.SlugField(default='', max_length=40),
        ),
    ]
