# Generated by Django 2.2.1 on 2019-07-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='session_id',
            field=models.CharField(blank=True, max_length=181),
        ),
    ]
